### PR TITLE
Make changes to check for broken links

### LINKED ISSUE #3: Add periodic check for broken links
Suggested by Julie. We can have a workflow that periodically goes through every url and see if a request to it fails. Interested parties could email-subscribe to failing GitHub Actions to be notified when one breaks, then check the logs to see which.

### PR DESCRIPTION
**Pull request by vincerubinetti**
@jmcmurry

Closes #3 

Note that there is a bit limitation to this, in that it only goes to the URL and checks the [status code](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status). If you go to a [broken Zoom link](https://zoom.us/j/12345abcdef), for example, this won't catch it because Zoom doesn't return the appropriate status code (it returns 200 as if everything is OK). For the specific case of Zoom, I could check the HTML on the page for the presence "Invalid meeting ID", but that is a brittle solution. They may change that warning text at some point, or even theoretically include the word "invalid" somewhere on a valid meeting page for some reason.

However, I ran this locally on the large Bridge2AI redirects, and it did seem to catch two non-existing Google docs. Just keep in mind that this is a _rough_ check. **There may be false positives/negatives**. As such, I split it up as a separate workflow check, so if you see the "encode" workflow fail, that is a critical error you definitely need to fix, but if you see the "check" workflow fail, you may be able to ignore that.

### CODE REVIEW

**Comment by vincerubinetti** [comment]
@falquaddoomi Poke for review. Not urgent at all, but I'd like to close the loop if you have time.

File: core.js
Comment (falquaddoomi) [inline core.js:1]: Is there a reason that the code in this file can't be wrapped in a function? I'd think it would be a bit more elegant to directly invoke the function that does all the heavy lifting after importing `core.js` than have it run as a significant side effect when it's imported.

If it's so `list` only gets populated once, you could perhaps keep `list` as a non-exported variable, and return it immediately at the beginning of the function if it's been already initialized, or run the function as normal (including setting `list`) if not.

File: .github/workflows/deploy.yaml [hunk 1]
```diff
@@ -15,25 +15,30 @@ env:
...
+        uses: actions/checkout@v4
         with:
           repository: ${{ github.repository_owner }}/${{ env.website_repo }} # assume same user/org
           path: website-repo # save in separate sub-folder
 
+      - name: Set up Bun
+        uses: oven-sh/setup-bun@v1
+
       - name: Install packages
-        run: npm install glob@v9 yaml@v2
```
Comment (falquaddoomi) [inline .github/workflows/deploy.yaml:33]: Neat to see that you're using bun; I'm curious if you've had a better experience with it than node so far.

**Review by falquaddoomi — APPROVED** [review]
I didn't see anything that would block approval, but I left a comment about `core.js`.

File: .github/workflows/deploy.yaml (hunk 1 above)
Comment (vincerubinetti) [reply .github/workflows/deploy.yaml:33]: So far it's been slightly faster than Node, and an [order of magnitude faster than Yarn](https://github.com/monarch-initiative/monarch-app/pull/624) with the same functionality.

File: core.js
Comment (vincerubinetti) [reply core.js:1]: I'll look into this, I was just keeping it flat for simplicity, and because the other functions (encode, and the script in the other repo) are the same way.

Comment (vincerubinetti) [reply core.js:1]: Added a commit that wraps things in functions. (almost) side-effect free now, and more modular to perhaps be reused/copied elsewhere.
